require:
  - rubocop-gitlab-security
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'bin/**/*'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/NestedGroups:
  MaxNesting: 4

Metrics/AbcSize:
  CountRepeatedAttributes: false
